### PR TITLE
Checking readability with LanguageTool (WIP)

### LINKED ISSUE #52: Use LanguageTool to check that language is easy to read

### PR DESCRIPTION
**Pull request by noatamir**
closes #52 

First pass for spellchecking an dsimple re-writes. Will then do another for simplifying the text.

### CODE REVIEW

**Comment by aterrel** [comment]
This seems to be no longer something that is being worked on. Can we go ahead and close it?

**Comment by mikofski** [comment]
This PR looks fine to me, but now there are conflicts with upstream, if resolved I think it should be merged

**Comment by aterrel** [comment]
Okay I'll fix the merge conflicts and merge it in.

**Review by aterrel — APPROVED** [review]
[Approval in comments](https://github.com/numfocus/DISCOVER-Cookbook/pull/66#issuecomment-2558898906)

**Comment by tkoyama010** [comment]
@all-contributors please add @mikofski for review

**Comment by tkoyama010** [comment]
@all-contributors please add @aterrel for review

**Pull request merged**
